[app]
name = "idea-pasha-bot"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  DB_PATH = "/data/ideas.db"

[mounts]
  source = "idea_bot_data"
  destination = "/data"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
